services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  webapi:
    build:
      context: ../
      dockerfile: DemoNotification.WebAPI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - kafka
    environment:
      - KafkaSettings__BootstrapServers=${KAFKA__BOOTSTRAPSERVERS}
    restart: on-failure

  notifservice:
    build:
      context: ../
      dockerfile: DemoNotification.NotificationSendService/Dockerfile
    depends_on:
      - kafka
    environment:
      - KafkaSettings__BootstrapServers=${KAFKA__BOOTSTRAPSERVERS}
      - SmtpSettings__Host=${SMTP__HOST}
      - SmtpSettings__Port=${SMTP__PORT}
      - SmtpSettings__Username=${SMTP__USERNAME}
      - SmtpSettings__Password=${SMTP__PASSWORD}
      - SmtpSettings__From=${SMTP__FROM}
    restart: on-failure